In [ ]:
import numpy as np
#np.linspace(start,stop,num-points)
#linespace function reates 1D array. 
#Use linespace as demonstrated above to create a 1D array "x" of 10 number-points. The values of elements be between 5 abd 6.
np.linspace(5,6,10)



array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [ ]:
I=np.eye(7)
#the above code of line will create an array of shape (7,7) with DIAGONAL values be '1'. Right?
#execute and verify
print(I.shape)
print(I)

(7, 7)
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#What if youwant to have an array with svalues other than '1' in DIAGONAL???
#Tyr .diag()
a=[1,2,3,4,5,6,7]
I=np.diag(a)
print(I)
#execute n see

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [ ]:
#create an array with diagonal values of [.2,.3,.5,.8,.9]
a=[.2,.3,.5,.8,.9]
I=np.diag(a)
print(I)


[[0.2 0.  0.  0.  0. ]
 [0.  0.3 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.8 0. ]
 [0.  0.  0.  0.  0.9]]


In [ ]:
#create arrays by using rand(), randn() and use seed() to set the seed value to 10000 before creating an array with random values, functions from np.random module

from numpy.random import seed
from numpy.random import rand
from numpy.random import randn



seed(10000)
a=rand(2,2)
print('a=',a)
b=randn(2,2)
print('b=',b)








a= [[0.54547015 0.17186532]
 [0.85293181 0.18022341]]
b= [[-0.97341942  0.227681  ]
 [-0.81932804  0.10722255]]


In [ ]:
c= 2+.1j
#c is a complex number in above example.
#create an array of shape 2,2 os complex numbers
from  numpy.random import rand
A=rand(2,2)
A_comp=A.view(dtype=np.complex128)
print("A_comp=",A_comp)



A_comp= [[0.85219857+0.78483787j]
 [0.91252121+0.68044154j]]


In [ ]:
import numpy as np
a = np.diag(np.arange(3))
#write code to fetch the third line, second column of the array 'a'.
print(a)
print("The third line, second column element is=",a[2][1])








[[0 0 0]
 [0 1 0]
 [0 0 2]]
The third line, second column element is= 0


In [ ]:
#Change the value  of the element at third line, second column of the array 'a'to 100
import numpy as np
a = np.diag(np.arange(3))
a[2][1]=100
print("The third line, second column element after change is=",a[2][1])
print("a=",a)




The third line, second column element after change is= 100
a= [[  0   0   0]
 [  0   1   0]
 [  0 100   2]]


In [ ]:
#Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. 
#Suppose we had a 8 × 4 array

arr = np.empty((8, 4))
print(arr)

#To select out a subset of the rows in a particular order, 
#you can simply pass a list or ndarray of integers specifying the desired order:

arr[[4, 3, 0, 6]]

# Using negative indices select rows from the end. write code to select elements of arr using negative indexing
print("The value in the last row and second column using negative indexing is=",arr[-1][-3])
print("The values in the last row using negative indexing is=",arr[-1][:])



[[4.68505532e-310 1.01777523e-321 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.14027814e+161 1.47762371e+248 4.30625279e-096]
 [1.12855837e+277 3.62607434e+228 8.37404121e+242 4.31999013e-096]
 [5.02034658e+175 3.96412100e-061 4.25699637e+174 2.74965756e+180]
 [1.22226585e+161 2.59027864e-144 7.79952704e-143 4.25756448e-096]
 [4.82337723e+228 5.34842273e-038 9.96663423e-047 9.60785076e-071]
 [4.51299432e-037 1.04917650e-153 1.94918966e-153 3.11548672e-033]
 [6.36696114e-062 7.86203985e-067 6.79767609e-310 0.00000000e+000]]
The value in the last row and second column using negative indexing is= 7.862039853832195e-67
The values in the last row using negative indexing is= [6.36696114e-062 7.86203985e-067 6.79767609e-310 0.00000000e+000]


In [ ]:
#how to use reshape()
arr = np.arange(40)
arr.reshape((8, 5))


#execute and analyse

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
#lets do this otherwise...
arr.reshape((5,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
# reshape the following array 'a1' into 9, 5 and then 5,9 shape
a1=np.arange(45)
b=a1.reshape((9,5))
print("b=",b)

c=a1.reshape((5,9))
print("c=",c)


b= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
c= [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]
